### ISSUE TITLE
Default should be to bind only to localhost 

### ISSUE THREAD

**Issue by lawrencesystems** [danicuestasuarez/NMapGUI#5]
The default run should be binding only to localhost to prevent others on the network accessing the service.

**Comment by daniel-cues** [comment]
Binded application to 127.0.0.1. Only can be accessed via localhost now.

As easy as this in the application.properties file:
`server.address=127.0.0.1`

[Commit](https://github.com/danicuestasuarez/NMapGUI/commit/e3e5d9686240dd04cd5f91a313d06d4fabf062fc)
[Release](https://github.com/danicuestasuarez/NMapGUI/releases/tag/v0.4.1)
